//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class centros_de_salud
    {
        public string codigo_centro { get; set; }
        public string nombre { get; set; }
        public string direcionCompleta { get; set; }
        public int codigoPostal { get; set; }
        public string provincia { get; set; }
        public string region { get; set; }
        public string horario { get; set; }
        public string calle { get; set; }
        public string ciudad { get; set; }
        public string urlAdicional { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
        public string web { get; set; }
        public long telefono { get; set; }
        public int id { get; set; }
    }
}
