//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class estados_parking
    {
        public int id { get; set; }
        public int disponible { get; set; }
        public System.DateTime fecha { get; set; }
        public int parkings_id { get; set; }
    
        public virtual parkings parkings { get; set; }
    }
}
