//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class farmacias
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
        public string direccion { get; set; }
        public string direccionAbreviada { get; set; }
        public string provincia { get; set; }
        public string ciudad { get; set; }
        public int codigoPostal { get; set; }
        public string url { get; set; }
        public long telefono { get; set; }
        public string web { get; set; }
        public string informacionAdcional { get; set; }
        public string nombrePropietario { get; set; }
    }
}
