//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class lineas_bilbobus
    {
        public lineas_bilbobus()
        {
            this.tiempos_linea_parada = new HashSet<tiempos_linea_parada>();
            this.viajes_bilbobus = new HashSet<viajes_bilbobus>();
        }
    
        public int id { get; set; }
        public string abreviatura { get; set; }
        public string nombre { get; set; }
        public int tipoTransporte { get; set; }
    
        public virtual ICollection<tiempos_linea_parada> tiempos_linea_parada { get; set; }
        public virtual ICollection<viajes_bilbobus> viajes_bilbobus { get; set; }
    }
}
