//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trip2bilbaoEntities : DbContext
    {
        public trip2bilbaoEntities()
            : base("name=trip2bilbaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<centros_de_salud> centros_de_salud { get; set; }
        public DbSet<entradas> entradas { get; set; }
        public DbSet<farmacias> farmacias { get; set; }
        public DbSet<hospitales> hospitales { get; set; }
        public DbSet<incidencias> incidencias { get; set; }
        public DbSet<lineas_bilbobus> lineas_bilbobus { get; set; }
        public DbSet<lineas_bizkaibus> lineas_bizkaibus { get; set; }
        public DbSet<lineas_euskotren> lineas_euskotren { get; set; }
        public DbSet<lineas_metro> lineas_metro { get; set; }
        public DbSet<paradas_bilbobus> paradas_bilbobus { get; set; }
        public DbSet<paradas_bizkaibus> paradas_bizkaibus { get; set; }
        public DbSet<paradas_euskotren> paradas_euskotren { get; set; }
        public DbSet<paradas_metro> paradas_metro { get; set; }
        public DbSet<paradas_tranvia> paradas_tranvia { get; set; }
        public DbSet<parkings> parkings { get; set; }
        public DbSet<puntos_bici> puntos_bici { get; set; }
        public DbSet<tarifas> tarifas { get; set; }
        public DbSet<tiempo_prediccion> tiempo_prediccion { get; set; }
        public DbSet<tiempos_ciudad> tiempos_ciudad { get; set; }
        public DbSet<tiempos_comarca> tiempos_comarca { get; set; }
        public DbSet<tiempos_dia> tiempos_dia { get; set; }
        public DbSet<tiempos_dia_ciudad> tiempos_dia_ciudad { get; set; }
        public DbSet<tiempos_dia_comarca> tiempos_dia_comarca { get; set; }
        public DbSet<tiempos_linea_parada> tiempos_linea_parada { get; set; }
        public DbSet<viajes_bilbobus> viajes_bilbobus { get; set; }
        public DbSet<viajes_bizkaibus> viajes_bizkaibus { get; set; }
        public DbSet<viajes_euskotren> viajes_euskotren { get; set; }
        public DbSet<viajes_metro> viajes_metro { get; set; }
        public DbSet<viajes_metro_has_paradas_metro> viajes_metro_has_paradas_metro { get; set; }
    }
}
