//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class paradas_metro
    {
        public paradas_metro()
        {
            this.paradas_metro1 = new HashSet<paradas_metro>();
            this.viajes_metro = new HashSet<viajes_metro>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string tipoLocalizacion { get; set; }
        public int paradas_metroId { get; set; }
    
        public virtual ICollection<paradas_metro> paradas_metro1 { get; set; }
        public virtual paradas_metro paradas_metro2 { get; set; }
        public virtual ICollection<viajes_metro> viajes_metro { get; set; }
    }
}
