//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class paradas_euskotren
    {
        public paradas_euskotren()
        {
            this.viajes_euskotren = new HashSet<viajes_euskotren>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string url { get; set; }
        public string tipoLocalizacion { get; set; }
    
        public virtual ICollection<viajes_euskotren> viajes_euskotren { get; set; }
    }
}
