//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class paradas_metro
    {
        public paradas_metro()
        {
            this.viajes_parada_tiempos_metro = new HashSet<viajes_parada_tiempos_metro>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
        public int tipoLocalizacion { get; set; }
        public string idParadaPadre { get; set; }
        public string codigoParada { get; set; }
        public string idParada { get; set; }
        public int codigoPostal { get; set; }
    
        public virtual ICollection<viajes_parada_tiempos_metro> viajes_parada_tiempos_metro { get; set; }
    }
}
