//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class parkings
    {
        public parkings()
        {
            this.entradas = new HashSet<entradas>();
            this.tarifas = new HashSet<tarifas>();
            this.estados_parking = new HashSet<estados_parking>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string tipo { get; set; }
        public System.DateTime fecha { get; set; }
        public string estado { get; set; }
        public int capacidad { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
    
        public virtual ICollection<entradas> entradas { get; set; }
        public virtual ICollection<tarifas> tarifas { get; set; }
        public virtual ICollection<estados_parking> estados_parking { get; set; }
    }
}
