//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class puntos_bici
    {
        public puntos_bici()
        {
            this.estados_puntobici = new HashSet<estados_puntobici>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string estado { get; set; }
        public double latitud { get; set; }
        public double longitud { get; set; }
        public int capacidad { get; set; }
        public int codigoPostal { get; set; }
    
        public virtual ICollection<estados_puntobici> estados_puntobici { get; set; }
    }
}
