//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifas
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public string zona { get; set; }
        public System.DateTime actualizacion { get; set; }
        public int parkingsId { get; set; }
    
        public virtual parkings parkings { get; set; }
    }
}
