//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiempos_dia_ciudad
    {
        public tiempos_dia_ciudad()
        {
            this.tiempos_ciudad = new HashSet<tiempos_ciudad>();
        }
    
        public int id { get; set; }
        public string nombreCiudad { get; set; }
        public System.DateTime fechaDescarga { get; set; }
    
        public virtual ICollection<tiempos_ciudad> tiempos_ciudad { get; set; }
    }
}
