//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiempos_ciudad
    {
        public int id { get; set; }
        public string diaPrediccion { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcionES { get; set; }
        public string descripcionEU { get; set; }
        public string descripcionGeneralES { get; set; }
        public string descripcionGeneralEU { get; set; }
        public int tiempos_dia_ciudad_id { get; set; }
        public int maxima { get; set; }
        public int minima { get; set; }
    
        public virtual tiempos_dia_ciudad tiempos_dia_ciudad { get; set; }
    }
}
