//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiempos_comarca
    {
        public tiempos_comarca()
        {
            this.tiempos_dia_comarca = new HashSet<tiempos_dia_comarca>();
        }
    
        public int id { get; set; }
        public System.DateTime diaActualizacion { get; set; }
        public string nombreComarcaES { get; set; }
        public string nombreComarcaEU { get; set; }
    
        public virtual ICollection<tiempos_dia_comarca> tiempos_dia_comarca { get; set; }
    }
}
