//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiempos_dia
    {
        public int id { get; set; }
        public System.DateTime fechaPrediccion { get; set; }
        public string vientoES { get; set; }
        public string vientoEU { get; set; }
        public string tiempoES { get; set; }
        public string tiempoEU { get; set; }
        public string temperaturaES { get; set; }
        public string temperaturaEU { get; set; }
        public int tiempo_prediccionId { get; set; }
        public int tiempos_prediccionId { get; set; }
    
        public virtual tiempos_prediccion tiempos_prediccion { get; set; }
    }
}
