//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiempos_prediccion
    {
        public tiempos_prediccion()
        {
            this.tiempos_dia = new HashSet<tiempos_dia>();
        }
    
        public int id { get; set; }
        public string fechaInicioPrediccion { get; set; }
        public string fechaFinPrediccion { get; set; }
        public string fechaRealizacionPrediccion { get; set; }
    
        public virtual ICollection<tiempos_dia> tiempos_dia { get; set; }
    }
}
