//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class viajes_parada_tiempos_bilbobus
    {
        public int Id { get; set; }
        public int viajes_bilbobus_id { get; set; }
        public int paradas_bilbobus_id { get; set; }
        public string tiempoLlegada { get; set; }
        public string tiempoSalida { get; set; }
    
        public virtual viajes_bilbobus viajes_bilbobus { get; set; }
        public virtual paradas_bilbobus paradas_bilbobus { get; set; }
    }
}
