//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class viajes_bilbobus
    {
        public viajes_bilbobus()
        {
            this.paradas_bilbobus = new HashSet<paradas_bilbobus>();
        }
    
        public int id { get; set; }
        public int lineas_bilbobusId { get; set; }
    
        public virtual ICollection<paradas_bilbobus> paradas_bilbobus { get; set; }
        public virtual lineas_bilbobus lineas_bilbobus { get; set; }
    }
}
