//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class viajes_euskotren
    {
        public viajes_euskotren()
        {
            this.paradas_euskotren = new HashSet<paradas_euskotren>();
        }
    
        public int id { get; set; }
        public int lineas_euskotrenId { get; set; }
    
        public virtual lineas_euskotren lineas_euskotren { get; set; }
        public virtual ICollection<paradas_euskotren> paradas_euskotren { get; set; }
    }
}
