//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almacenamiento
{
    using System;
    using System.Collections.Generic;
    
    public partial class viajes_euskotren
    {
        public viajes_euskotren()
        {
            this.viajes_parada_tiempos = new HashSet<viajes_parada_tiempos>();
        }
    
        public int id { get; set; }
        public int lineas_euskotrenId { get; set; }
        public string idViaje { get; set; }
        public string tiempoInicio { get; set; }
        public string tiempoFin { get; set; }
    
        public virtual lineas_euskotren lineas_euskotren { get; set; }
        public virtual ICollection<viajes_parada_tiempos> viajes_parada_tiempos { get; set; }
    }
}
