//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8662
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeustoParking2014
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityDTO", Namespace="http://schemas.datacontract.org/2004/07/DeustoParking2014")]
    public partial class ActivityDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short DBSCounterField;
        
        private System.DateTime FechaField;
        
        private short GRALCounterField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short DBSCounter
        {
            get
            {
                return this.DBSCounterField;
            }
            set
            {
                this.DBSCounterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short GRALCounter
        {
            get
            {
                return this.GRALCounterField;
            }
            set
            {
                this.GRALCounterField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StadisticDTO", Namespace="http://schemas.datacontract.org/2004/07/DeustoParking2014")]
    public partial class StadisticDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short[] DBSCounterField;
        
        private short[] GRALCounterField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short[] DBSCounter
        {
            get
            {
                return this.DBSCounterField;
            }
            set
            {
                this.DBSCounterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short[] GRALCounter
        {
            get
            {
                return this.GRALCounterField;
            }
            set
            {
                this.GRALCounterField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDeustoParkingService")]
public interface IDeustoParkingService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeustoParkingService/GetLastActivity", ReplyAction="http://tempuri.org/IDeustoParkingService/GetLastActivityResponse")]
    DeustoParking2014.ActivityDTO GetLastActivity();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeustoParkingService/GetStadistic", ReplyAction="http://tempuri.org/IDeustoParkingService/GetStadisticResponse")]
    DeustoParking2014.StadisticDTO GetStadistic(System.DateTime Fecha);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeustoParkingService/PutActivity", ReplyAction="http://tempuri.org/IDeustoParkingService/PutActivityResponse")]
    void PutActivity(short DBSCounter, short GRALCounter, string tokeId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDeustoParkingServiceChannel : IDeustoParkingService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DeustoParkingServiceClient : System.ServiceModel.ClientBase<IDeustoParkingService>, IDeustoParkingService
{
    
    public DeustoParkingServiceClient()
    {
    }
    
    public DeustoParkingServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DeustoParkingServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeustoParkingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DeustoParkingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DeustoParking2014.ActivityDTO GetLastActivity()
    {
        return base.Channel.GetLastActivity();
    }
    
    public DeustoParking2014.StadisticDTO GetStadistic(System.DateTime Fecha)
    {
        return base.Channel.GetStadistic(Fecha);
    }
    
    public void PutActivity(short DBSCounter, short GRALCounter, string tokeId)
    {
        base.Channel.PutActivity(DBSCounter, GRALCounter, tokeId);
    }
}
